-- Complete seed data for all 50 grapes (25 red + 25 white)

DELETE FROM grapes; -- Clear any existing data

INSERT INTO grapes (id, name, alternative_names, color, style, aromas, origin, styles, aging, food_pairing, display_order) VALUES
-- RED GRAPES (1-25)
('cabernet-sauvignon', 'Cabernet Sauvignon', NULL, 'red',
  'Fyllig till mycket fyllig, hög tannin, medel till hög syra och ofta relativt hög alkohol. Stram i ung ålder, med tydlig struktur och ibland kantiga tanniner som behöver tid eller mat.',
  'Svarta vinbär, cassis, plommon, körsbär, ceder, grafit, tobak, paprika (grön capsicum) i svalare klimat; med mognad kommer läder, cigarrlåda och torkade örter.',
  'Ursprung i Bordeaux (framför allt Médoc), idag globalt spridd: Napa Valley, Chile (Maipo, Colchagua), Australien (Coonawarra, Margaret River), Sydafrika, Italien, Spanien m.fl.',
  'Ofta ryggrad i klassiska Bordeauxblandningar; görs både som druvrent vin och i cuvéer med Merlot, Cabernet Franc m.fl. Vanligt med ekfatslagring.',
  'Mycket god. Kvalitetsviner från klassiska områden kan utvecklas i 10–30 år, ibland längre. Enklare stilar är mer tänkta att drickas inom 3–8 år.',
  'Perfekt till grillat och stekt nötkött, biff, entrecôte, lamm, vilt, mustiga grytor och lagrade, hårda ostar. De kraftigare, fatlagrade vinerna trivs med fetare tillbehör.',
  0),
('merlot', 'Merlot', NULL, 'red',
  'Medelfyllig till fyllig, medel syra och mjukare tanniner än Cabernet. Ofta rund, fruktig och lättare att uppskatta i ung ålder.',
  'Plommon, körsbär, skogsbär, choklad, lakrits, örter och ibland kaffe och vanilj från fat. I svalare klimat mer röda bär och örtighet, i varmare mer mörk frukt och syltighet.',
  'Bordeaux (särskilt högra stranden: Pomerol, Saint‑Émilion); idag även i t.ex. Kalifornien, Chile, Italien (särskilt Toscana), Östeuropa.',
  'Druvrent eller i Bordeauxblends. Merlot används ofta för att mjuka upp stram Cabernet. Stil från fruktdriven och ekad "Nya världen" till mer strukturerat och jordigt "Gamla världen".',
  'Bra kvalitetsmerlot kan lagras 8–15 år eller mer, särskilt från klassiska appellationer. Enklare viner är bäst inom 3–6 år.',
  'Flexibel matdruva: lamm, fläsk, kyckling, hamburgare, köttfärsrätter, pasta med tomat eller svamp, medelstarka ostar.',
  1),
('pinot-noir', 'Pinot Noir', NULL, 'red',
  'Lätt till medelfyllig, hög syra, låga till medel tanniner. Elegant och känslig druva som tydligt speglar terroir.',
  'Röda bär – jordgubb, hallon, körsbär – tillsammans med blommighet (viol, ros) och ofta skogsgolv, svamp, undervegetation vid mognad. Kan få inslag av rök, kryddor och vanilj från fat.',
  'Bourgogne är referensen (Côte d''Or), men odlas också i t.ex. Oregon, Kalifornien, Nya Zeeland, Tyskland (Spätburgunder) och Chile.',
  'Främst eleganta, torra röda viner; druvans släktingar används också i Champagne‑blend (Pinot Noir och Pinot Meunier). Känslig i vinifiering – ofta varsam extraktion och relativt lätt ek.',
  'Toppviner från Bourgogne och andra kvalitetsregioner kan utvecklas i 10–25 år. Enklare stilar är som bäst inom 3–8 år.',
  'Kombineras gärna med fågel (anka, kyckling), vildfågel, kalv, fläsk, svampbaserade rätter, lax och tonfisk. En favorit till klassisk fransk bistro‑mat.',
  2),
('syrah', 'Syrah', ARRAY['Shiraz'], 'red',
  'Medel till fyllig, medel syra, medel till hög tannin. Kan upplevas kraftfull men också elegant beroende på ursprung.',
  'Mörka bär (björnbär, blåbär), plommon, svartpeppar, lakrits, rökt kött och ibland oliver. I varmare klimat mer syltig frukt och choklad; i svalare mer peppar och florala toner.',
  'Norra Rhône (Côte‑Rôtie, Hermitage) är klassiskt. I Nya världen ofta kallad Shiraz, särskilt i Australien (Barossa, McLaren Vale), Sydafrika, USA och Chile.',
  'Allt från strama, svala Syrah till koncentrerade, rika Shiraz. Används druvrent eller i GSM‑blends (Grenache–Syrah–Mourvèdre). Vanlig med ekfatslagring.',
  'Högklassig Syrah/Shiraz kan lagras 10–20 år eller mer. Enklare, fruktiga viner mår bra att drickas inom 3–7 år.',
  'Utmärkt till grillat, BBQ, lamm, vilt, kryddiga korvar, mustiga grytor och smakrika ostar. De peppriga, svalare exemplen fungerar fint till pepparstek och rätter med örter.',
  3),
('grenache', 'Grenache', ARRAY['Garnacha'], 'red',
  'Medelfyllig till fyllig, relativt låg syra och mjuka tanniner, ofta med hög alkohol. Silkig textur när den är välgjord.',
  'Jordgubb, hallon, körsbär, torkade örter, apelsinskal, garrigue (medelhavsörtighet) och ibland vitpeppar. Vid högre koncentration – torkad frukt och choklad.',
  'Ursprunget anses vara Spanien (Garnacha), men är också mycket viktig i södra Rhône (Châteauneuf‑du‑Pape, Côtes‑du‑Rhône), Priorat, Campo de Borja och Languedoc.',
  'Vanlig i blends (GSM), men även som druvrent vin och i rosé. Tunnskalig, vilket ger lättare färg men hög alkohol och fyllig frukt.',
  'Bästa exemplen från t.ex. Châteauneuf‑du‑Pape och Priorat kan lagras 10–20 år. Lättare, fruktiga versioner är godast inom 3–6 år.',
  'Passar fint till lamm, grillat, medelhavskök, grönsaksrätter, ratatouille, tapas och halvhårda ostar.',
  4),
('tempranillo', 'Tempranillo', NULL, 'red',
  'Medel till fyllig, medel syra och medel tannin. Texturen varierar från frisk och fruktig till tät och ekkryddig beroende på lagring.',
  'Körsbär, plommon, jordgubb, torkad frukt, tobak, läder, vanilj och dill (särskilt från amerikansk ek i Rioja). Vid mognad – fikon, läder, nötighet.',
  'Spaniens signaturdruva. Viktigast i Rioja, Ribera del Duero, Toro, Navarra och flera andra regioner; även planterad i Portugal (som Tinta Roriz/Aragonez).',
  'Från unga, fruktiga Joven till ekfatslagrade Crianza, Reserva och Gran Reserva. Kan vara både druvrent och blandat med t.ex. Garnacha och Graciano.',
  'Reserva och Gran Reserva från topproducenter kan utvecklas i 10–25 år. Enklare stilar är utmärkta inom 3–7 år.',
  'Perfekt till tapas, grillat kött, charkuterier, lamm, paella, hårdostar och grytor med tomat och paprika.',
  5),
('sangiovese', 'Sangiovese', NULL, 'red',
  'Medel till fyllig, hög syra, medel till hög tannin. Elegant med påtaglig struktur – behöver ofta mat eller lagring för att tanniner och syra ska balansera.',
  'Sur körsbär, plommon, viol, örter, te, läder och jordighet. Eklagring tillför vanilj, kryddor och tobak.',
  'Italiens viktigaste röda druva. Mest känd från Toscana: Chianti, Brunello di Montalcino, Vino Nobile di Montepulciano och Super Tuscans.',
  'Allt från lättare, friskare Chianti till kraftigare Brunello och Rosso di Montalcino. Kan vara druvrent eller blandat med t.ex. Canaiolo eller internationella druvor.',
  'Kvalitets‑Sangiovese (särskilt Brunello och Riserva) kan lagras 10–30 år. Enklare Chianti är bäst inom 3–8 år.',
  'Pasta med tomatsås, ragu, grillat kött, biff, kalvkött, hårdostar (särskilt Pecorino och Parmigiano), pizza och tomatbaserade rätter.',
  6),
('nebbiolo', 'Nebbiolo', NULL, 'red',
  'Medelfyllig till fyllig (trots ljusare färg), mycket hög syra och mycket hög tannin. Kräver ofta lång tid i fat och flaska för att tämjas. Komplex och elegant när den är mogen.',
  'Rosor, violer, tjära, lakrits, körsbär, tryffel, läder, undervegetation. Med mognad ofta körsbärslikör och torkade blommor.',
  'Främst Piemonte: Barolo, Barbaresco och mindre appellationer som Roero och Gattinara. Mindre mängder även i Valtellina (Lombardiet).',
  'Ofta druvrent. Traditionellt lång maceration och lagring i stora trä‑fat; modernare stilar kan vara mer koncentrerade med kortare maceration. Alltid hög struktur.',
  'Mycket hög. Barolo och Barbaresco kan utvecklas 15–40 år, ibland längre. Riserva‑versioner kräver ofta en dekad eller mer för att nå sin topp.',
  'Braserat nötkött, vilt (rådjur, vildsvin), tryffelrätter, risotto, agnolotti, lagrade hårda ostar (Parmigiano, Grana Padano) och magra styckdetaljer.',
  7),
('barbera', 'Barbera', NULL, 'red',
  'Medel till fyllig, mycket hög syra, relativt låga tanniner. Frisk och saftig, ibland med hög fruktighet.',
  'Körsbär, plommon, bär, svarta oliver, örter och kryddor. Ekfat tillför vanilj och kaffe.',
  'Piemonte är kärnan (Barbera d''Asti, Barbera d''Alba), men odlas även i Emilia‑Romagna, Lombardiet och delar av Nya världen.',
  'Från lättare, fruktigare viner utan ek till mer strukturerade, fatlagrade varianter. Alltid med tydlig syra.',
  'De flesta är tänkta att drickas unga, inom 3–7 år. Toppviner med ek kan utvecklas 10–15 år.',
  'Fungerar utmärkt till syrarika tomatbaserade rätter, pasta, risotto, pizza, grillade grönsaker och charkuterier.',
  8),
('malbec', 'Malbec', NULL, 'red',
  'Medelfyllig till fyllig, medel syra, mjuka tanniner. Frodig fruktighet och rund textur.',
  'Mörka bär (björnbär, blåbär), plommon, choklad, kaffe, viol, kryddor och ibland tobak från fat.',
  'Ursprung i Cahors (sydvästra Frankrike), men idag mest känd från Argentina – särskilt Mendoza. Även i Chile och andra nya regioner.',
  'Ofta druvrent i Argentina, där det görs både fruktigt och koncentrerat. I Cahors mer stram och jordnära stil.',
  'Argentinsk Malbec är ofta bäst inom 3–8 år, men kvalitetsviner kan utvecklas 10–15 år. Klassisk Cahors kan lagras ännu längre.',
  'Perfekt till grillat kött (asado), biff, lamm, hamburgare, köttfärsrätter, empanadas och hårdare ostar.',
  9),
('zinfandel', 'Zinfandel', ARRAY['Primitivo'], 'red',
  'Medelfyllig till mycket fyllig, medel syra, medel till höga tanniner. Ofta hög alkohol (14–16+ %) och koncentrerad frukt.',
  'Mörk frukt (björnbär, plommon), körsbär, kryddor (svartpeppar, kanel), vanilj, kakao och ibland russin/syltig frukt.',
  'Kalifornien är modernt hem (Sonoma, Paso Robles, Lodi). Ursprungligen från Kroatien (Crljenak Kaštelanski). I Italien känd som Primitivo (Puglia).',
  'Allt från friska, måttligt alkoholstarka viner till kraftiga "monster Zins". Även White Zinfandel (off‑dry rosé) är vanlig. I Italien ofta lättare stil.',
  'De flesta är bäst unga, inom 3–7 år. Mer balanserade, kvalitativa exemplar kan utvecklas 10–15 år.',
  'BBQ, grillat, hamburgare, BBQ‑ribs, pizza, kryddiga rätter, medelstarka ostar och charkuterier.',
  10),
('cabernet-franc', 'Cabernet Franc', NULL, 'red',
  'Lätt till medelfyllig, medel till hög syra, medel tannin. Lättare och mer örtigt än Cabernet Sauvignon, men med en viss elegans.',
  'Röda bär, körsbär, plommon, paprika (särskilt grön), örter, viol och ibland grafit. I varmare klimat mer fruktdriven.',
  'Loire‑dalen (Chinon, Bourgueil, Saumur‑Champigny) och höger strand i Bordeaux (Saint‑Émilion, Pomerol). Även i Nya världen, t.ex. USA och Chile.',
  'Kan göras både druvrent (särskilt i Loire) och som viktigt blendkomponent i Bordeaux och världen över. Ofta elegant och örtigt.',
  'Kvalitetsviner från Loire och Bordeaux kan utvecklas 8–15 år. Enklare viner är godast inom 3–7 år.',
  'Rillettes, charkuterier, grillade grönsaker, fläsk, grillad lax, kyckling, kryddiga rätter och mjuka ostar.',
  11),
('gamay', 'Gamay', NULL, 'red',
  'Lätt till medelfyllig, hög syra, låga tanniner. Ofta saftig och lättdrucken med levande fruktighet.',
  'Röda bär – jordgubb, hallon, körsbär, blommighet och ibland banan/tuggummi (från kolsyrajäsning).',
  'Beaujolais i Bourgogne är klassiskt (inkl. de tio Cru‑byarna). Även i Loire och Schweiz (Genève).',
  'Från lätt och fruktig Beaujolais Nouveau till mer strukturerad Beaujolais Cru. Ofta kolsyrajäsning (carbonic maceration) för fruktdrift.',
  'Beaujolais Nouveau dricks omedelbart. De flesta Gamay är godast inom 2–5 år. Cru‑viner kan utvecklas 5–10 år.',
  'Utmärkt till charkuterier, kycklingrätter, grillad fisk, vegetariska rätter, svamprisotto och mjuka ostar. Serveras ofta kyld.',
  12),
('mourvedre', 'Mourvèdre', ARRAY['Monastrell'], 'red',
  'Medelfyllig till fyllig, medel syra, höga tanniner. Ofta robust och köttig textur.',
  'Mörka bär (björnbär, blåbär), plommon, vilt, läder, kött, örter, lakrits och ibland rökighet.',
  'Spanien (Monastrell, särskilt i Jumilla och Yecla). I Frankrike viktig del i södra Rhône (Bandol, Châteauneuf‑du‑Pape). Även i Californien och Australien.',
  'Används både druvrent (Bandol, Jumilla) och i GSM‑blends (Grenache–Syrah–Mourvèdre). Kräver varmt klimat för att mogna.',
  'Kvalitets‑Mourvèdre (t.ex. Bandol) kan lagras 10–20 år. Enklare viner är bäst inom 4–8 år.',
  'Grillade köttbitar, lamm, vilt, kryddiga korvar, grytor, BBQ och kraftfulla, hårdare ostar.',
  13),
('pinotage', 'Pinotage', NULL, 'red',
  'Medelfyllig till fyllig, medel syra, medel till höga tanniner. Varierar från fruktig och lättdrucken till kraftig och ekig.',
  'Röda bär, plommon, jordiga toner, rök, kaffe, choklad och ibland gummi/aceton vid överdriven vinifiering.',
  'Sydafrika (korsning mellan Pinot Noir och Cinsault från 1925). Framför allt Stellenbosch och Paarl.',
  'Stor stilvariation – från färsk och fruktig "café‑stil" till tung, ekfatslagrad "Cape Blend". Kan vara både druvrent och i blends.',
  'De flesta är godast inom 3–7 år. Mer strukturerade versioner kan utvecklas 8–12 år.',
  'BBQ, biltong, hamburgare, grillat kött, kryddiga korvar, stuvningar och medelstarka ostar.',
  14),
('carignan', 'Carignan', NULL, 'red',
  'Medelfyllig till fyllig, hög syra, höga tanniner. Kan vara sträv och mörk i ung ålder, men gammelvinstockar ger koncentration och elegans.',
  'Mörka bär, plommon, örter, kryddor, jordighet, ibland violer och lakrits.',
  'Ursprung i Spanien (Cariñena, Priorat som Samsó). Viktig i södra Frankrike (Languedoc, Roussillon). Även i Chile och Kalifornien.',
  'Används ofta i blends för att tillföra struktur och syra, men kan också göras druvrent från gamla stockar.',
  'Kvalitetsviner från gamla stockar kan utvecklas 8–15 år. Enklare viner är bäst inom 3–6 år.',
  'Grytor, grillat, lamm, kryddiga rätter, medelhavskök, tapas och hårdostar.',
  15),
('cinsault', 'Cinsault', NULL, 'red',
  'Lätt till medelfyllig, medel syra, låga tanniner. Mjuk och fruktdriven, ofta elegant.',
  'Röda bär (jordgubb, hallon, körsbär), blommighet, örter och lätt kryddig ton.',
  'Sydfrankrike (Languedoc, Rhône) och Sydafrika. Även i Libanon och Nordafrika.',
  'Används ofta i blends (särskilt i rosé) och sällan druvrent. Ger mjukhet och fruktighet utan tung struktur.',
  'De flesta viner är bäst unga, inom 2–5 år.',
  'Lätta kötträtter, kyckling, charkuterier, grillade grönsaker, sommarsallader och mild ost.',
  16),
('touriga-nacional', 'Touriga Nacional', NULL, 'red',
  'Medelfyllig till fyllig, medel syra, höga tanniner. Koncentrerad och strukturerad, med aromatisk komplexitet.',
  'Mörka bär (björnbär, blåbär), viol, rosor, bergamott, lakrits, sten och ibland eukalyptus.',
  'Portugal, särskilt Douro‑dalen och Dão. Viktig i både portvinstillverkning och torra röda viner.',
  'Druvrent eller i blends (ofta med Touriga Franca, Tinta Roriz). Görs både som druvrent torrt vin och som bas i portvin.',
  'Kvalitets‑Touriga Nacional kan utvecklas 10–20 år. Enklare viner är bäst inom 4–8 år.',
  'Grillat kött, lamm, vilt, kraftfulla grytor, portugalensis kök (bacalhau, cozido) och hårdostar.',
  17),
('corvina', 'Corvina', NULL, 'red',
  'Medelfyllig, medel syra, låga till medel tanniner. Ofta elegant med en viss bitterhet i eftersmaken (mandel).',
  'Sur körsbär, körsbär, röda bär, mandel, örter och ibland torkad frukt (i Amarone).',
  'Venetoregionen i Italien – viktigaste druvan i Valpolicella, Bardolino och Amarone.',
  'Används i blends med Rondinella och Molinara. Stilar från lätt Valpolicella till kraftig, torkad‑druvstil Amarone och Ripasso.',
  'Valpolicella är bäst ung, inom 2–5 år. Ripasso 5–10 år. Amarone kan lagras 15–30 år eller mer.',
  'Pasta, risotto, kalvkött, anka, fågel, polenta och mjuka till medelstarka ostar. Amarone fungerar även till vilt och lagrade hårda ostar.',
  18),
('nero-davola', 'Nero d''Avola', NULL, 'red',
  'Medelfyllig till fyllig, medel syra, medel till höga tanniner. Ofta kraftfull och varm med mogen frukt.',
  'Mörka körsbär, plommon, björnbär, kryddor, choklad, tobak och ibland örter.',
  'Siciliens viktigaste röda druva, särskilt från Noto och sydöstra delarna.',
  'Druvrent eller i blends. Stil från fruktig och lättare till kraftig och ekfatslagrad.',
  'Kvalitetsviner kan utvecklas 8–15 år. Enklare viner är bäst inom 3–7 år.',
  'Pasta med köttsås, grillat kött, lamm, sicilianska rätter, auberginerätter och hårdostar.',
  19),
('dolcetto', 'Dolcetto', NULL, 'red',
  'Lätt till medelfyllig, låg syra, medel tannin. Mjuk och fruktig med viss bitterhet i finish.',
  'Svarta körsbär, plommon, violer, mandel och örter.',
  'Piemonte, särskilt Dolcetto d''Alba, Dolcetto d''Asti och Dolcetto di Dogliani.',
  'Druvrent, ofta relativt enkelt och färskt. Tänkt att drickas ung.',
  'De flesta är bäst inom 2–5 år.',
  'Charkuterier, pizza, pasta, grillade grönsaker, vardagsmat och mjuka ostar.',
  20),
('bobal', 'Bobal', NULL, 'red',
  'Medelfyllig till fyllig, medel syra, höga tanniner. Mörk färg och koncentrerad frukt.',
  'Mörka bär, plommon, örter, kryddor och jordighet.',
  'Östspanien, främst Utiel‑Requena i Valencia. Används även för rosé och cava.',
  'Druvrent eller i blends. Ofta använd som färg‑ och strukturdruva. Även vanlig i rosé.',
  'Kvalitetsviner kan utvecklas 8–12 år. Enklare viner är bäst inom 3–6 år.',
  'Paella, grillat kött, tapas, grytor och medelstarka ostar.',
  21),
('tannat', 'Tannat', NULL, 'red',
  'Fyllig, medel syra, mycket höga tanniner. Ofta robust och kraftfull.',
  'Mörka bär (björnbär, blåbär), plommon, viol, läder, kryddor och ibland choklad.',
  'Ursprung i sydvästra Frankrike (Madiran). Idag mest känd från Uruguay.',
  'Druvrent eller i blends. Kräver ofta lång lagring för att tämja tanninerna.',
  'Kvalitets‑Tannat kan lagras 10–20 år eller mer. Enklare stilar är bäst inom 5–10 år.',
  'Grillat kött, lamm, vilt, fetare kötträtter, asado och hårdostar.',
  22),
('aglianico', 'Aglianico', NULL, 'red',
  'Fyllig, hög syra, mycket höga tanniner. Kräver ofta lång mognad. Kallas ibland "söderns Nebbiolo".',
  'Mörka körsbär, plommon, tjära, läder, örter, svartpeppar och jordighet.',
  'Södra Italien, särskilt Taurasi (Kampanien) och Aglianico del Vulture (Basilicata).',
  'Druvrent. Traditionellt lång lagring i stora fat. Kräver tid för att mjukna.',
  'Mycket hög – kvalitetsviner kan lagras 15–30 år eller mer.',
  'Vilt, lamm, mustig pasta, grillat kött, lagrade ostar och kraftfulla italienska rätter.',
  23),
('pinot-meunier', 'Pinot Meunier', NULL, 'red',
  'Lätt till medelfyllig, medel syra, låga tanniner. Mjukare och mer omedelbart tillgänglig än Pinot Noir.',
  'Röda bär, äpple, blommighet och ibland örter.',
  'Champagne‑regionen, där den är en av tre huvuddruvor (tillsammans med Pinot Noir och Chardonnay). Även i vissa tyska områden (Schwarzriesling).',
  'Främst i mousserande vin (Champagne), sällan druvrent. Tillför fruktighet och mjukhet till blends.',
  'Som stilla vin är det bäst ungt, inom 2–5 år. I Champagne bidrar det till vinets ungdomliga fruktighet.',
  'Som del av Champagne: skaldjur, lättare förrätter, sushi, aperitif.',
  24),

-- WHITE GRAPES (26-50)
('chardonnay', 'Chardonnay', NULL, 'white',
  'Medel till fyllig, medel syra. En kameleont som kan vara allt från stram och mineraldriven till rik, smörig och ekad.',
  'I svalare klimat: citrus, grönt äpple, mineral. I varmare: gul frukt, tropisk frukt. Med ek och malolaktisk jäsning – smör, vanilj, rostad nöt, brioche.',
  'Ursprung i Bourgogne (Chablis, Côte de Beaune). Idag global: Kalifornien, Australien, Nya Zeeland, Sydafrika, Chile, m.fl.',
  'Torra vita viner, både stilla och mousserande (huvuddruva i många Champagner och andra bubbel). Stor variation i ek och vinmakning.',
  'Kvalitets‑Chardonnay från Bourgogne och topp‑Nya världen kan lagras 10–20 år. Enklare viner är godast inom 2–6 år.',
  'Oekad/sval Chardonnay till skaldjur, fisk, ostron. Fylligare, fatad stil till kyckling, kalv, smöriga såser, svamprätter och milda ostar.',
  25),
('sauvignon-blanc', 'Sauvignon Blanc', NULL, 'white',
  'Lätt till medelfyllig, hög syra, frisk och aromatisk.',
  'Citrus, lime, krusbär, nässlor, svartvinbärsblad, tropisk frukt (passionsfrukt) i varmare klimat, samt ofta örtiga och mineraliska toner.',
  'Loire (Sancerre, Pouilly‑Fumé) och Bordeaux (blends). Nya Zeeland (Marlborough) är modern stilikon; även Chile, Sydafrika, Kalifornien.',
  'Oftast torr, ståltanksjäst för att bevara aromatik. I Bordeaux blandas den ofta med Sémillon, både i torra och söta viner.',
  'De flesta viner är som bäst unga, inom 2–5 år, men kvalitetsviner från Loire och fatlagrad Sauvignon kan utvecklas 8–10 år.',
  'Fantastisk till getost, sallader, sparris, skaldjur, ceviche, sushi, lättare fiskrätter och rätter med mycket gröna örter.',
  26),
('riesling', 'Riesling', NULL, 'white',
  'Lätt till medelfyllig, mycket hög syra. Kan vara allt från knastertorr till ljupt söt.',
  'Lime, citron, grönt äpple, stenfrukt, blommighet. Vid mognad ofta petroleum/"diesel", honung och torkad frukt.',
  'Tyskland (Mosel, Rheingau, Pfalz, Nahe), Alsace, Österrike (Wachau, Kremstal) och Australien (Clare, Eden Valley).',
  'Stor stilbredd: torr, halvtorr, söt, ädelrötad, mousserande. Ofta ståltanksjäst för att bevara ren frukt.',
  'Mycket hög, särskilt för kvalitetsviner. Torra topp‑Riesling kan utvecklas 10–20 år, ädelrötade ännu längre.',
  'Torr Riesling till fisk, skaldjur, sashimi, lätta rätter. Halvtorr/söt Riesling är utmärkt till asiatisk och kryddstark mat, samt foie gras och starkare ostar.',
  27),
('pinot-grigio', 'Pinot Grigio', ARRAY['Pinot Gris'], 'white',
  'Lätt till medelfyllig, medel till hög syra. Pinot Grigio (italiensk stil) är lättare och fräschare, Pinot Gris (Alsace‑stil) fylligare och mer aromatisk.',
  'Citrus, grönt äpple, päron, blommor, mineraler. Alsace‑stil kan ha honung, kryddor och tropisk frukt.',
  'Italien (främst Veneto, Trentino‑Alto Adige, Friuli) och Alsace. Även i Oregon, Nya Zeeland och Tyskland.',
  'Lättare italiensk stil (Pinot Grigio) vs fylligare, ibland ekad Alsace‑stil (Pinot Gris).',
  'De flesta är bäst unga, inom 2–4 år. Alsace‑versioner kan utvecklas 5–8 år.',
  'Pinot Grigio: sallader, lättare fiskrätter, skaldjur, sushi. Pinot Gris: fläsk, fjäderfä, smöriga såser, svamp.',
  28),
('chenin-blanc', 'Chenin Blanc', NULL, 'white',
  'Lätt till medelfyllig, mycket hög syra. Stor stilvariation från knastertorr till ljuvligt söt.',
  'Grönt äpple, päron, honung, blomster, quince, chamomile, våt ull. Med ålder – honung, bivax, torkad frukt.',
  'Loire‑dalen (Vouvray, Savennières, Anjou) är klassisk. Viktig i Sydafrika. Även i Kalifornien och Argentina.',
  'Torr, halvtorr, söt (ädelrötad), mousserande. Används även till destillat. Stor variation beroende på terroir och vinifiering.',
  'Mycket hög. Kvalitets‑Chenin från Loire och Sydafrika kan utvecklas 10–30 år eller mer.',
  'Torr Chenin: fisk, fjäderfä, skaldjur, grönsaksrätter. Söt Chenin: foie gras, desserter, blåmögelost.',
  29),
('gewurztraminer', 'Gewürztraminer', NULL, 'white',
  'Medelfyllig, låg till medel syra, ofta lite högre alkohol. Mycket aromatisk och expressiv.',
  'Lychee, ros, parfym, kryddor (ingefära, kanel), tropisk frukt, honung. Intensivt aromatisk.',
  'Alsace är klassiskt, men odlas även i Tyskland, Italien (Alto Adige), Östeuropa, Nya Zeeland och USA.',
  'Kan vara torr, halvtorr eller söt (vendange tardive, sélection de grains nobles). Ofta låg syra men hög aromatik.',
  'De flesta är bäst unga, inom 3–6 år. Toppviner från Alsace kan utvecklas 8–15 år.',
  'Asiatisk mat (thai, indisk), kryddstark mat, foie gras, starka ostar (Munster), rökta rätter.',
  30),
('viognier', 'Viognier', NULL, 'white',
  'Medelfyllig till fyllig, låg syra, ofta hög alkohol. Fyllig textur och aromatisk.',
  'Aprikos, persika, honungsmelon, blommor (viol, kaprifol), kryddor och ibland mineraler.',
  'Norra Rhône (Condrieu, Château‑Grillet). Även i Languedoc, Kalifornien, Australien och Chile.',
  'Oftast torr och druvrent, ibland ekfatslagrad. Används även som små tillsatser i röda Syrah‑viner (Côte‑Rôtie).',
  'De flesta är bäst unga, inom 2–5 år. Kvalitetsviner från Condrieu kan utvecklas 5–10 år.',
  'Skaldjur (hummer, krabba), fisk med rika såser, fjäderfä, kryddiga asiatiska rätter, mjuka ostar.',
  31),
('semillon', 'Sémillon', NULL, 'white',
  'Medelfyllig, låg till medel syra. Fyllig textur, särskilt när ekad eller ädelrötad.',
  'Citrus, grönt äpple, honung, bivax, fikon, nötter. Ädelrötad version: marmelad, honung, aprikos.',
  'Bordeaux (både torra och söta viner – Sauternes, Barsac) och Australien (Hunter Valley).',
  'Torr (ofta blend med Sauvignon Blanc), söt ädelrötad (Sauternes), eller druvrent. Kan vara oekad eller ekad.',
  'Torra viner: 3–8 år. Ädelrötad Sémillon (Sauternes) kan lagras 20–50 år eller mer.',
  'Torr Sémillon: fisk, skaldjur, fjäderfä. Söt Sémillon: foie gras, blåmögelost, fruktdesserter.',
  32),
('albarino', 'Albariño', ARRAY['Alvarinho'], 'white',
  'Lätt till medelfyllig, hög syra, frisk och aromatisk.',
  'Citrus, persika, aprikos, blommor, saltvattenton, mineraler.',
  'Rías Baixas i Galicien (nordvästra Spanien) och Vinho Verde i Portugal (som Alvarinho).',
  'Oftast torr, ståltanksjäst, fräsch och fruktig. Ibland kortare kontakt med jästfällningar för mer textur.',
  'De flesta är bäst unga, inom 2–4 år.',
  'Utmärkt till skaldjur, ostron, fisk, ceviche, tapas och lättare sallader.',
  33),
('verdejo', 'Verdejo', NULL, 'white',
  'Lätt till medelfyllig, medel till hög syra. Frisk och aromatisk.',
  'Citrus, grönt äpple, fänkål, örter, tropisk frukt, ibland nötter och cremighet från jästkontakt.',
  'Rueda i Kastilien och León, Spanien.',
  'Oftast torr och ståltanksjäst, ibland med jästkontakt eller lätt ek för mer textur.',
  'De flesta är bäst unga, inom 2–4 år.',
  'Tapas, skaldjur, fisk, sallader, vitare kötträtter, grillad bläckfisk.',
  34),
('gruner-veltliner', 'Grüner Veltliner', NULL, 'white',
  'Lätt till medelfyllig, hög syra, frisk och kryddig.',
  'Citrus, grönt äpple, vit peppar, örter, mineraler. Toppviner kan ha honung och nötighet.',
  'Österrike, särskilt Wachau, Kamptal, Kremstal och Wien.',
  'Från lättare, fräscha viner till mer koncentrerade och ekade versioner. Ofta ståltank.',
  'Enklare viner: 2–4 år. Kvalitetsviner (särskilt från Wachau) kan utvecklas 8–15 år.',
  'Schnitzel, fisk, skaldjur, sparris, grönsaksrätter, asiatisk mat, getost.',
  35),
('moscato', 'Moscato', ARRAY['Muscat'], 'white',
  'Lätt, låg alkohol (ofta 5–7%), söt eller halvtorr. Aromatisk och lättdrucken.',
  'Druva, persika, aprikos, citrus, blommor, honung. Mycket aromatisk och fruktig.',
  'Italien (Moscato d''Asti, Asti Spumante), Frankrike (Muscat de Beaumes‑de‑Venise), Spanien, Grekland.',
  'Söt mousserande (Moscato d''Asti), torr mousserande (Asti), torra vita viner, likörvin (Muscat).',
  'De flesta är bäst unga och färska, inom 1–3 år.',
  'Desserter, frukt, lätta kakor, aperitif. Moscato d''Asti är perfekt till panettone.',
  36),
('glera', 'Glera', NULL, 'white',
  'Lätt, hög syra, frisk och fruktig. Huvuddruvan i Prosecco.',
  'Grönt äpple, päron, citrus, vita blommor, honung.',
  'Venetoregionen i Italien, särskilt Prosecco DOCG (Conegliano‑Valdobbiadene).',
  'Främst mousserande (Prosecco), ibland stilla vin. Charmat‑metoden (tank) för att bevara fruktighet.',
  'Bäst ung och färsk, inom 1–2 år.',
  'Aperitif, lättare förrätter, skaldjur, risotto, aperol spritz.',
  37),
('trebbiano', 'Trebbiano', ARRAY['Ugni Blanc'], 'white',
  'Lätt till medelfyllig, hög syra, neutral i smak.',
  'Citrus, grönt äpple, blommor. Ofta neutral och frisk.',
  'Italien (Trebbiano) och Frankrike (Ugni Blanc). Använd i Cognac och Armagnac, samt i många italienska vita viner.',
  'Stilla vita viner, ofta i blends. Viktig för destillat (Cognac, Armagnac).',
  'De flesta är bäst unga, inom 2–3 år.',
  'Fisk, skaldjur, lätta pastarätter, sallader.',
  38),
('garganega', 'Garganega', NULL, 'white',
  'Medelfyllig, medel syra, kan vara både frisk och fyllig.',
  'Citrus, mandel, vita blommor, honung. I Recioto‑stil: torkad frukt, honung.',
  'Venetoregionen, Italien. Huvuddruvan i Soave.',
  'Torr (Soave), söt (Recioto di Soave). Från enkel ståltank till mer komplex ekad stil.',
  'Enklare Soave: 2–4 år. Kvalitets‑Soave Classico kan utvecklas 5–10 år.',
  'Fisk, risotto, fjäderfä, mandel‑baserade rätter, mjuka ostar.',
  39),
('verdicchio', 'Verdicchio', NULL, 'white',
  'Medelfyllig, hög syra, frisk och mineralisk.',
  'Citrus, grönt äpple, mandel, örter, saltvattenton, mineraler.',
  'Marche‑regionen, Italien (Verdicchio dei Castelli di Jesi, Verdicchio di Matelica).',
  'Oftast torr, ståltanksjäst. Kan också vara ekad eller sparkling.',
  'Enklare viner: 2–5 år. Kvalitetsviner kan utvecklas 5–10 år.',
  'Skaldjur, fisk, friterad fisk (fritto misto), pasta med skaldjur.',
  40),
('fiano', 'Fiano', NULL, 'white',
  'Medelfyllig, medel syra, fyllig textur och aromatisk.',
  'Honung, nötter, päron, aprikos, örter, mineraler.',
  'Kampanien, södra Italien (Fiano di Avellino).',
  'Torr, ofta ståltank, ibland ekad. Kan utveckla nötig komplexitet.',
  'De flesta är bäst inom 3–6 år. Kvalitetsviner kan utvecklas 8–12 år.',
  'Fisk, skaldjur, fjäderfä, pasta med nötsås, milda ostar.',
  41),
('vermentino', 'Vermentino', NULL, 'white',
  'Lätt till medelfyllig, hög syra, frisk och aromatisk.',
  'Citrus, grönt äpple, vita blommor, örter, saltvattenton.',
  'Sardinien, Ligurien (som Pigato), Toscana (som Vermentino) och Korsika (som Rolle).',
  'Oftast torr, fräsch och fruktig. Ibland ekad för mer textur.',
  'De flesta är bäst unga, inom 2–4 år.',
  'Skaldjur, fisk, pesto, medelhavskök, sallader.',
  42),
('torrontes', 'Torrontés', NULL, 'white',
  'Lätt till medelfyllig, medel syra, aromatisk och fruktig.',
  'Blommor (ros, jasmin), lychee, persika, citrus, muskat.',
  'Argentina, särskilt Salta och La Rioja (argentinska).',
  'Torr, aromatisk, ståltanksjäst. Liknar Gewürztraminer i aromintensitet.',
  'Bäst ung, inom 2–4 år.',
  'Asiatisk mat, kryddstark mat, skaldjur, ceviche, aperitif.',
  43),
('godello', 'Godello', NULL, 'white',
  'Medelfyllig, hög syra, mineralisk och elegant.',
  'Citrus, stenfrukt, örter, mineraler, ibland nötig ton från ek.',
  'Galicien, nordvästra Spanien (Valdeorras, Bierzo).',
  'Torr, ofta ståltank, ibland ekad. Allt mer populär för sin elegans.',
  'De flesta är bäst inom 3–6 år. Ekade versioner kan utvecklas 6–10 år.',
  'Fisk, skaldjur, fjäderfä, grillade grönsaker, tapas.',
  44),
('cortese', 'Cortese', NULL, 'white',
  'Lätt till medelfyllig, hög syra, frisk och mineralisk.',
  'Citrus, grönt äpple, vita blommor, mineraler.',
  'Piemonte, Italien (Gavi/Cortese di Gavi).',
  'Torr, ståltanksjäst, fräsch. Ibland ekad eller jästkontakt.',
  'De flesta är bäst unga, inom 2–4 år.',
  'Skaldjur, fisk, risotto, pesto, lättare pastarätter.',
  45),
('marsanne', 'Marsanne', NULL, 'white',
  'Medelfyllig till fyllig, låg till medel syra, rik textur.',
  'Honungsmelon, aprikos, mandel, blommor, honung.',
  'Norra Rhône (Hermitage, Crozes‑Hermitage, Saint‑Joseph), ofta tillsammans med Roussanne.',
  'Torr, ofta ekad. Används i blends med Roussanne och Viognier.',
  'Kvalitetsviner kan utvecklas 8–15 år.',
  'Fisk med rika såser, fjäderfä, svamp, nötbaserade rätter.',
  46),
('roussanne', 'Roussanne', NULL, 'white',
  'Medelfyllig, medel syra, aromatisk och komplex.',
  'Örter, päron, honung, te, blommor, mineraler.',
  'Norra Rhône (Hermitage, Châteauneuf‑du‑Pape), ofta tillsammans med Marsanne.',
  'Torr, ofta ekad. Används i blends eller druvrent.',
  'Kvalitetsviner kan utvecklas 8–15 år.',
  'Fisk, skaldjur, fjäderfä, medelstarka ostar, komplex vegetarisk mat.',
  47),
('airen', 'Airén', NULL, 'white',
  'Lätt, låg syra, neutral. Världens mest planterade vita druva (ytvise).',
  'Neutral, lätta citrusnoter.',
  'La Mancha, Spanien.',
  'Enkla, färska vita viner. Används även för destillat (Brandy de Jerez).',
  'Bäst mycket ung, inom 1–2 år.',
  'Enkla rätter, tapas, vardagsdryck.',
  48),
('palomino-fino', 'Palomino Fino', NULL, 'white',
  'Neutral som stilla vin, men huvuddruva för Sherry.',
  'Som stilla vin: neutral, mandel. Som Sherry: mandel, jäst, salt, oxidativa toner.',
  'Jerez, Andalusien, Spanien.',
  'Främst Sherry (Fino, Manzanilla, Amontillado, Oloroso). Sällan som stilla vin.',
  'Som Sherry varierar lagring kraftigt – från några år till decennier.',
  'Fino/Manzanilla: tapas, skaldjur, oliver. Oloroso: nötter, charkuterier, kraftfullare rätter.',
  49);
